### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by liu2-3zhi** [Rsplwe/ESurfingDialer#55]
换了一个版本都是这个错误。好奇怪啊

`[05:03:25 158]  INFO [com.rsplwe.esurfing.Client] (Client:143) - Keep Retry: 15
[05:03:25 158]  INFO [com.rsplwe.esurfing.Client] (Client:77) - The network has been connected.
[05:03:40 169]  INFO [com.rsplwe.esurfing.Client] (Client:33) - Send Keep Packet
[05:03:40 171]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:03:40 171]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:03:40 172]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:03:40 172]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:03:40 202]  INFO [com.rsplwe.esurfing.Client] (Client:35) - Next Retry: 
Exception in thread "Thread-2" java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Long.parseLong(Long.java:595)
        at java.base/java.lang.Long.parseLong(Long.java:722)
        at com.rsplwe.esurfing.Client.run(Client.kt:32)
        at java.base/java.lang.Thread.run(Thread.java:1570)`

**Comment by Rsplwe** [comment]
有尝试 1.6.0 版本吗

**Comment by liu2-3zhi** [comment]
> 有尝试 1.6.0 版本吗

1.6.0连认证都认证不了，一直提示无法解析10000.gd.cn和onnect.rom.miui.com，改hosts都没有用，我甚至把从wan获取到的dns设置成默认dns都不行。目前也就只有1.5.0可用完成认证，但是无法发送心跳包

**Comment by liu2-3zhi** [comment]
1.4.0发着发着也报错了

`[05:16:25 582]  INFO [com.rsplwe.esurfing.Client] (Client:35) - Next Retry: 480
[05:24:25 647]  INFO [com.rsplwe.esurfing.Client] (Client:33) - Send Keep Packet
[05:24:25 649]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:24:25 650]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:24:25 650]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:24:25 650]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:24:25 729]  INFO [com.rsplwe.esurfing.Client] (Client:35) - Next Retry: 480
[05:32:25 871]  INFO [com.rsplwe.esurfing.Client] (Client:33) - Send Keep Packet
[05:32:25 873]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:32:25 873]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:32:25 873]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[05:32:25 873]  INFO [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:490) - fork
[05:32:25 913]  INFO [com.rsplwe.esurfing.Client] (Client:35) - Next Retry: 
Exception in thread "Thread-2" java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Long.parseLong(Long.java:595)
        at java.base/java.lang.Long.parseLong(Long.java:722)
        at com.rsplwe.esurfing.Client.run(Client.kt:32)
        at java.base/java.lang.Thread.run(Thread.java:1570)`

**Comment by Rsplwe** [comment]
能用 wireshark 抓下程序运行时的包，然后发到我邮箱吗

**Comment by liu2-3zhi** [comment]
> 能用 wireshark 抓下程序运行时的包，然后发到我邮箱吗

我不清楚你要抓什么包......是认证的时候的数据包？

**Comment by liu2-3zhi** [comment]
我刚刚又去测速了一下1.6.0

还是错误

[05:49:22 832]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #1
[05:49:22 835]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://connect.rom.miui.com/generate_204
[05:49:22 835]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:22 873]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #2
[05:49:22 873]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://enet.10000.gd.cn:10001/?wlanuserip=172.19.237.182&wlanacip=14.148.0.67
[05:49:22 874]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:22 890]  INFO [com.rsplwe.esurfing.Client] (Client:43) - The network has been connected.
[05:49:28 099]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #3
[05:49:28 099]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://connect.rom.miui.com/generate_204
[05:49:28 100]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:28 121]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #4
[05:49:28 121]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://enet.10000.gd.cn:10001/?wlanuserip=172.19.237.182&wlanacip=14.148.0.67
[05:49:28 122]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:28 133]  INFO [com.rsplwe.esurfing.Client] (Client:43) - The network has been connected.
[05:49:33 342]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #5
[05:49:33 342]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://connect.rom.miui.com/generate_204
[05:49:33 342]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:33 361]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #6
[05:49:33 361]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://enet.10000.gd.cn:10001/?wlanuserip=172.19.237.182&wlanacip=14.148.0.67
[05:49:33 361]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:33 374]  INFO [com.rsplwe.esurfing.Client] (Client:43) - The network has been connected.
[05:49:38 583]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #7
[05:49:38 583]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://connect.rom.miui.com/generate_204
[05:49:38 583]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:38 602]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #8
[05:49:38 602]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://enet.10000.gd.cn:10001/?wlanuserip=172.19.237.182&wlanacip=14.148.0.67
[05:49:38 602]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:38 613]  INFO [com.rsplwe.esurfing.Client] (Client:43) - The network has been connected.
[05:49:43 821]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #9
[05:49:43 821]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://connect.rom.miui.com/generate_204
[05:49:43 821]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:43 845]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:28) - Redirect #10
[05:49:43 845]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:29) - Url: http://enet.10000.gd.cn:10001/?wlanuserip=172.19.237.182&wlanacip=14.148.0.67
[05:49:43 845]  INFO [com.rsplwe.esurfing.network.RedirectInterceptor] (RedirectInterceptor:30) - Response Code: 302
[05:49:43 856]  INFO [com.rsplwe.esurfing.Client] (Client:43) - The network has been connected.
[05:49:49 067] ERROR [ConnectivityStatus] (NetworkConnectivityKt:78) - java.lang.RuntimeException: Request Code: 302
        at com.rsplwe.esurfing.utils.NetworkConnectivityKt.detectConfig(NetworkConnectivity.kt:40)
        at com.rsplwe.esurfing.Client.run(Client.kt:32)
        at com.rsplwe.esurfing.DialerApp.main(DialerApp.kt:72)

[05:49:54 285] ERROR [ConnectivityStatus] (NetworkConnectivityKt:78) - java.lang.RuntimeException: Request Code: 302
        at com.rsplwe.esurfing.utils.NetworkConnectivityKt.detectConfig(NetworkConnectivity.kt:40)
        at com.rsplwe.esurfing.Client.run(Client.kt:32)
        at com.rsplwe.esurfing.DialerApp.main(DialerApp.kt:72)

[05:49:59 495] ERROR [ConnectivityStatus] (NetworkConnectivityKt:78) - java.lang.RuntimeException: Request Code: 302
        at com.rsplwe.esurfing.utils.NetworkConnectivityKt.detectConfig(NetworkConnectivity.kt:40)
        at com.rsplwe.esurfing.Client.run(Client.kt:32)
        at com.rsplwe.esurfing.DialerApp.main(DialerApp.kt:72)

**Comment by Rsplwe** [comment]
> 我不清楚你要抓什么包......是认证的时候的数据包？

程序运行时到程序结束范围内的

**Comment by liu2-3zhi** [comment]
> > 我不清楚你要抓什么包......是认证的时候的数据包？
> 
> 程序运行时到程序结束范围内的

这个周期有亿点点长，特别是1.4.0，不知道哪个心跳包发着发着就没有下次时间了，然后错误了

**Comment by liu2-3zhi** [comment]
刚刚点错了

**Comment by Rsplwe** [comment]
由于我现在已经不在学校了，所以没有相关的网络环境来调试错误，如果要反馈错误只能先抓包再发送给我

**Comment by liu2-3zhi** [comment]
服务器就只在登录的时候返回了KeepRetry，后面都不返回了。有点时候甚至登录都不返回，索性添加校验功能，如果不符合，则默认60秒。

**Comment by liu2-3zhi** [comment]
[06:12:03 295]  INFO [com.rsplwe.esurfing.Client] (Client:80) - The login has been authorized.
[06:12:18 992]  INFO [com.rsplwe.esurfing.Client] (Client:37) - Send Keep Packet
[06:12:19 259]  INFO [com.rsplwe.esurfing.Client] (Client:39) - Next Retry: 480
[06:20:19 452]  INFO [com.rsplwe.esurfing.Client] (Client:37) - Send Keep Packet
[06:20:19 554]  WARN [com.rsplwe.esurfing.Client] (Client:205) - KeepRetry value is incorrect after heartbeat, setting to default: 60
[06:20:19 554]  INFO [com.rsplwe.esurfing.Client] (Client:39) - Next Retry: 60
[06:21:20 103]  INFO [com.rsplwe.esurfing.Client] (Client:37) - Send Keep Packet
[06:21:20 207]  WARN [com.rsplwe.esurfing.Client] (Client:205) - KeepRetry value is incorrect after heartbeat, setting to default: 60
[06:21:20 207]  INFO [com.rsplwe.esurfing.Client] (Client:39) - Next Retry: 60
[06:22:20 629]  INFO [com.rsplwe.esurfing.Client] (Client:37) - Send Keep Packet
[06:22:20 753]  WARN [com.rsplwe.esurfing.Client] (Client:205) - KeepRetry value is incorrect after heartbeat, setting to default: 60
[06:22:20 753]  INFO [com.rsplwe.esurfing.Client] (Client:39) - Next Retry: 60
[06:23:21 478]  INFO [com.rsplwe.esurfing.Client] (Client:37) - Send Keep Packet
[06:23:21 585]  WARN [com.rsplwe.esurfing.Client] (Client:205) - KeepRetry value is incorrect after heartbeat, setting to default: 60
[06:23:21 586]  INFO [com.rsplwe.esurfing.Client] (Client:39) - Next Retry: 60

**Comment by liu2-3zhi** [comment]
好家伙，还得我自己close

**Comment by 250king** [comment]
我也遇到相似的情况，我到时候也去看看现在怎么样了

**Comment by 250king** [comment]
然后我看了一下，有些心跳包是已经停了好几个小时，都没有日志输出了（但有网？）
我今晚回去再试着复现

**Comment by 250king** [comment]
有时候因为网络波动导致测试请求失败抛出Exception，然后卡在那边一直不动了，就哪怕后来经检测可以ping但也不会继续发心跳包了
感觉好像是有一个bug，就是限制他继续运行

**Comment by liu2-3zhi** [comment]
> 我也遇到相似的情况，我到时候也去看看现在怎么样了 就我部署了两个拨号端的，一个是共享连接的Windows挂着拨号器，另一个openwrt用该项目。就看总体稳定性，感觉openwrt有点不稳定，具体体现在Windows那边正常，另一边断了

我怀疑你使用了UA修改插件

**Comment by 250king** [comment]
UA修改？都是只用于Release的Jar

**Comment by liu2-3zhi** [comment]
UA2F或者UA3F等

**Comment by 250king** [comment]
我没用啊，我现在打算用Debian试一下
